spring:
  application :
    name : fastdfs-service
  jmx:
    enabled: false
  http:
    multipart:
      enabled: true
      file-size-threshold: 0
      max-file-size: 4Mb
      max-request-size: 10Mb
  redis:
    database: 0
    host: 192.168.16.26
    port: 6379
    password: gdotc888
    max-active: 8
    max-wait: -1
    max-idle: 8
    min-idle: 0
    timeout: 0
server:
  port : 8087

fdfs:
  soTimeout: 1500
  connectTimeout: 600
  thumbImage:             #缩略图生成参数
    width: 150
    height: 150
  trackerList:            #TrackerList参数,支持多个
    - 192.168.16.26:22122



